CREATE TABLE IF NOT EXISTS products (
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`name` VARCHAR(255) NOT NULL,
`description` VARCHAR(255) NOT NULL,
`price` DECIMAL(10,2) NOT NULL,
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`quantity` INT NOT NULL,
`image` VARCHAR(255) NOT NULL,

 PRIMARY KEY (id)
);